"""C / C++ CRC generator.

Emits a ``(header, source)`` tuple of complete, compilable files.
The header uses the standard ``#ifdef __cplusplus`` ``extern "C"``
guard so the same code drops into both C and C++ projects without
manual name-mangling fix-ups.  The source ``#include``s the header
and additionally emits an ``<fname>_self_test()`` function returning
0 on success / 1 on failure -- callable from a firmware test
framework, boot self-check, factory burn-in, or termapy's CI
runner harness.  No ``main()`` is emitted so the file links cleanly
alongside the user's own entry point.

Verified at build time by ``tests.test_crc_codegen_exec
.TestGeneratedCExecutes``, which writes the pair to a tmpdir,
synthesizes a tiny runner that calls ``_self_test()``, compiles with
``gcc -std=c99 -Wall -Werror``, and asserts the binary returns 0.
"""

# ruff: noqa: F541  - f-strings without placeholders used for code alignment

from __future__ import annotations

from termapy.protocol.crc import CRC_CATALOGUE, _reflect
from termapy.protocol.crcgen._helpers import (
    _build_table,
    _func_name,
    _hex,
    _mask,
)


def _format_table_c(table: list[int], width: int, ctype: str) -> str:
    """Format a lookup table as a C ``static const`` array."""
    hex_w = (width + 3) // 4
    lines = [f"static const {ctype} crc_table[256] = {{"]
    for row in range(0, 256, 8):
        vals = ", ".join(
            f"0x{table[i]:0{hex_w}X}" for i in range(row, min(row + 8, 256))
        )
        comma = "," if row + 8 < 256 else ""
        lines.append(f"    {vals}{comma}")
    lines.append("};")
    return "\n".join(lines)


def _self_test_c(fname: str, ctype: str, check: int, width: int) -> str:
    """Emit a C self-test function returning 0 on success, 1 on failure.

    Designed to be called from a downstream test framework, firmware
    boot self-check, or termapy's CI runner harness.  We deliberately
    do NOT emit a ``main()`` so the file drops into firmware without
    a symbol collision.
    """
    lines = [
        f"int {fname}_self_test(void) {{",
        f'    static const uint8_t kCheckInput[] = "123456789";',
        f"    return {fname}(kCheckInput, 9) == {_hex(check, width)} ? 0 : 1;",
        f"}}",
    ]
    return "\n".join(lines)


def _header_c(name: str, fname: str, ctype: str, desc: str) -> str:
    """Emit the ``.h`` header with ``extern "C"`` guard for C++ interop.

    Pulls in ``<stdint.h>`` and ``<stddef.h>`` so the implementation
    ``.c`` only needs ``#include "<fname>.h"`` -- callers (and
    termapy's pytest runner) don't have to know which headers the
    function body needs.
    """
    guard = f"{fname.upper()}_H"
    lines = [
        f"/* {fname}.h -- generated by termapy from reveng/{name}",
        f" * {desc}",
        f" */",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
        f"#include <stdint.h>",
        f"#include <stddef.h>",
        f"",
        f"#ifdef __cplusplus",
        f'extern "C" {{',
        f"#endif",
        f"",
        f"{ctype} {fname}(const uint8_t *data, size_t len);",
        f"int {fname}_self_test(void);",
        f"",
        f"#ifdef __cplusplus",
        f"}}",
        f"#endif",
        f"",
        f"#endif /* {guard} */",
    ]
    return "\n".join(lines)


def generate_c(name: str, table: bool = False) -> tuple[str, str] | None:
    """Generate a C ``.h`` + ``.c`` pair for a CRC algorithm.

    Returns a ``(header, source)`` tuple of complete, compilable files.
    The header uses the standard ``#ifdef __cplusplus`` ``extern "C"``
    guard so the same code drops into C and C++ projects with no
    name-mangling workarounds.  The source ``#include``s the header
    and additionally emits an ``<fname>_self_test()`` function that
    returns 0 on success / 1 on failure -- call from your test
    framework, boot self-check, factory burn-in, or termapy's CI
    runner harness.  No ``main()`` is emitted, so the file links
    cleanly alongside your firmware's own entry point.

    Args:
        name: Algorithm name from CRC_CATALOGUE.
        table: If True, emit the table-driven implementation instead
            of the bit-by-bit form.

    Returns:
        ``(header_source, impl_source)`` tuple of strings, or None if
        the algorithm name is unknown.
    """
    entry = CRC_CATALOGUE.get(name)
    if entry is None:
        return None

    w = entry["width"]
    poly = entry["poly"]
    init = entry["init"]
    refin = entry["refin"]
    refout = entry["refout"]
    xorout = entry["xorout"]
    check = entry["check"]
    desc = entry.get("desc", "")
    fname = _func_name(name)
    mask = _mask(w)

    if w <= 8:
        ctype = "uint8_t"
    elif w <= 16:
        ctype = "uint16_t"
    elif w <= 32:
        ctype = "uint32_t"
    else:
        ctype = "uint64_t"

    lines = []
    lines.append(f'/* {fname}.c -- generated by termapy from reveng/{name}')
    lines.append(f' * {desc}')
    lines.append(f' * check: crc("123456789") == {_hex(check, w)}')
    lines.append(f' *')
    lines.append(f' * Verify by calling {fname}_self_test() (returns 0 on success).')
    lines.append(f' */')
    lines.append(f'#include "{fname}.h"')
    lines.append(f'')
    if table:
        tbl = _build_table(w, poly, refin)
        lines.append(_format_table_c(tbl, w, ctype))
        lines.append("")
    lines.append(f"{ctype} {fname}(const uint8_t *data, size_t len) {{")

    if table:
        if refin:
            ref_init = _reflect(init, w)
            lines.append(f"    {ctype} crc = {_hex(ref_init, w)};")
            lines.append("    for (size_t i = 0; i < len; i++)")
            lines.append(
                "        crc = crc_table[(crc ^ data[i]) & 0xFF] ^ (crc >> 8);"
            )
        else:
            lines.append(f"    {ctype} crc = {_hex(init, w)};")
            lines.append("    for (size_t i = 0; i < len; i++)")
            # Parenthesize the second operand fully -- gcc's -Wparentheses
            # (in -Wall) rejects ``a ^ b & c`` as ambiguous even though
            # C's precedence rules give the same result.  Embedded devs
            # routinely build with -Wall -Werror, so the generator must
            # produce code that survives that.  (Caught by the execution
            # tests in test_crc_codegen_exec.py via the -Werror gcc flag.)
            lines.append(
                f"        crc = crc_table[((crc >> {w - 8}) ^ data[i]) & 0xFF] ^ ((crc << 8) & {mask});"
            )
    elif refin:
        ref_poly = _reflect(poly, w)
        ref_init = _reflect(init, w)
        lines.append(f"    {ctype} crc = {_hex(ref_init, w)};")
        lines.append(f"    for (size_t i = 0; i < len; i++) {{")
        lines.append(f"        crc ^= data[i];")
        lines.append(f"        for (int j = 0; j < 8; j++) {{")
        lines.append(f"            if (crc & 1)")
        lines.append(f"                crc = (crc >> 1) ^ {_hex(ref_poly, w)};")
        lines.append(f"            else")
        lines.append(f"                crc >>= 1;")
        lines.append(f"        }}")
        lines.append(f"    }}")
    else:
        lines.append(f"    {ctype} crc = {_hex(init, w)};")
        lines.append(f"    for (size_t i = 0; i < len; i++) {{")
        lines.append(f"        crc ^= ({ctype})data[i] << {w - 8};")
        lines.append(f"        for (int j = 0; j < 8; j++) {{")
        lines.append(f"            if (crc & {_hex(1 << (w - 1), w)})")
        lines.append(f"                crc = (crc << 1) ^ {_hex(poly, w)};")
        lines.append(f"            else")
        lines.append(f"                crc <<= 1;")
        lines.append(f"            crc &= {mask};")
        lines.append(f"        }}")
        lines.append(f"    }}")

    if refout != refin:
        lines.append(f"    /* reflect output */")
        lines.append(f"    {ctype} reflected = 0;")
        lines.append(f"    for (int k = 0; k < {w}; k++)")
        lines.append(f"        reflected |= ((crc >> k) & 1) << ({w - 1} - k);")
        lines.append(f"    crc = reflected;")

    if xorout:
        lines.append(f"    return crc ^ {_hex(xorout, w)};")
    else:
        lines.append(f"    return crc;")
    lines.append(f"}}")
    lines.append("")
    lines.append(_self_test_c(fname, ctype, check, w))

    header = _header_c(name, fname, ctype, desc)
    source = "\n".join(lines)
    return header, source
