"""VHDL CRC generator.

Emits a single ``.vhd`` file containing a package with two functions:

- ``<fname>(data: std_logic_vector) return std_logic_vector`` --
  the algorithm; input is a packed byte vector whose length must be
  a multiple of 8.
- ``<fname>_self_test return boolean`` -- runs the algorithm against
  the canonical reveng check string ``"123456789"`` and reports
  whether the result matches.  Designed to be called from a
  testbench process via ``assert`` (termapy's pytest harness
  synthesizes that testbench to verify the generator).

Scope note: simulator-friendly VHDL (pure functions over
``std_logic_vector``).  Compiles and simulates under GHDL and is
enough to verify correctness against the reveng catalogue.
Synthesizable FPGA hardware (pipelined entity / architecture) is a
future enhancement -- the function-in-package form is the right
shape for a "verified reference implementation"; a hardware
designer will typically want to wrap a synthesizable wrapper
around it.

Verified at build time by ``tests.test_crc_codegen_exec
.TestGeneratedVhdlExecutes``.
"""

# ruff: noqa: F541  - f-strings without placeholders used for code alignment

from __future__ import annotations

from termapy.protocol.crc import CRC_CATALOGUE, _reflect
from termapy.protocol.crcgen._helpers import _func_name, _hex


def _vhdl_lit(value: int, width: int) -> str:
    """Format an integer constant as a VHDL ``unsigned``-compatible literal.

    Hex bit-string literals (``x"..."``) are used when ``width`` is a
    multiple of 4 because they are width-explicit (no need to pass the
    size separately) and don't suffer from ``to_unsigned``'s ``natural``
    range limit -- which silently rejects values >= 2^31 with a
    runtime bound-check failure.  That bites every 32-bit CRC whose
    init / poly / check value happens to exceed 0x7FFFFFFF
    (most of them: 0xFFFFFFFF is a common init).

    For widths that aren't a multiple of 4 (e.g. CRC-5, CRC-12), the
    max possible value fits in ``natural``, so ``to_unsigned`` is
    safe and we keep using it.
    """
    if width % 4 == 0:
        hex_w = width // 4
        return f'x"{value:0{hex_w}X}"'
    return f"to_unsigned({value}, {width})"


def _self_test_vhdl(fname: str, check: int, width: int) -> str:
    """Emit a VHDL self-test function returning ``true`` / ``false``.

    Designed to be called from a testbench process via ``assert ...
    severity failure`` -- termapy's pytest harness synthesizes that
    testbench at test time (see ``test_crc_codegen_exec.py``).
    """
    lines = [
        f"    -- Run the canonical reveng check value; returns true on success.",
        f"    function {fname}_self_test return boolean is",
        f'        constant kCheckInput: std_logic_vector(71 downto 0) :=',
        f'            x"313233343536373839";  -- ASCII "123456789"',
        f"    begin",
        f"        return unsigned({fname}(kCheckInput)) = "
        f"{_vhdl_lit(check, width)};",
        f"    end function;",
    ]
    return "\n".join(lines)


def generate_vhdl(name: str, table: bool = False) -> str | None:
    """Generate a VHDL package implementing a CRC algorithm.

    Emits a single ``.vhd`` file containing a package with two
    functions: ``<fname>(data) return std_logic_vector`` and
    ``<fname>_self_test return boolean``.  See the module docstring
    for the scope note on simulator-friendly vs synthesizable.

    Args:
        name: Algorithm name from CRC_CATALOGUE.
        table: Accepted for API symmetry with the other generators
            but ignored -- the bit-by-bit form is always emitted.
            Table-driven VHDL adds nontrivial code-gen for the
            256-entry constant array without earning much in
            simulator mode; deferred to a future pass.

    Returns:
        VHDL source string, or None if the algorithm is unknown.
    """
    _ = table  # currently unused (see scope note in module docstring)
    entry = CRC_CATALOGUE.get(name)
    if entry is None:
        return None

    w = entry["width"]
    poly = entry["poly"]
    init = entry["init"]
    refin = entry["refin"]
    refout = entry["refout"]
    xorout = entry["xorout"]
    check = entry["check"]
    desc = entry.get("desc", "")
    fname = _func_name(name)
    pkg = f"{fname}_pkg"

    if refin:
        init_val = _reflect(init, w)
        poly_val = _reflect(poly, w)
    else:
        init_val = init
        poly_val = poly

    header = [
        f"-- {fname}.vhd -- generated by termapy from reveng/{name}",
        f"-- {desc}",
        f"-- check: crc(\"123456789\") == {_hex(check, w)}",
        f"--",
        f"-- Call {fname}_self_test from a testbench to verify "
        f"against the reveng check value.",
        f"",
        f"library ieee;",
        f"use ieee.std_logic_1164.all;",
        f"use ieee.numeric_std.all;",
        f"",
        f"package {pkg} is",
        f"    -- Compute CRC over a packed byte vector "
        f"(length must be a multiple of 8).",
        f"    function {fname}(data: std_logic_vector) "
        f"return std_logic_vector;",
        f"    function {fname}_self_test return boolean;",
        f"end package;",
        f"",
        f"package body {pkg} is",
    ]

    body = [
        f"    function {fname}(data: std_logic_vector) "
        f"return std_logic_vector is",
        f"        variable crc: unsigned({w - 1} downto 0) := "
        f"{_vhdl_lit(init_val, w)};",
        f"        variable byte: unsigned(7 downto 0);",
        f"        -- Normalize indexing regardless of caller's slice direction.",
        f"        constant d: std_logic_vector(data'length - 1 downto 0) := data;",
        f"        constant n: natural := data'length / 8;",
    ]

    if refout != refin:
        body.append(
            f"        variable reflected: unsigned({w - 1} downto 0);"
        )

    body += [
        f"    begin",
        f"        for i in 0 to n - 1 loop",
        f"            byte := unsigned("
        f"d((n - i)*8 - 1 downto (n - i - 1)*8));",
    ]

    if refin:
        body += [
            f"            crc := crc xor resize(byte, {w});",
            f"            for j in 0 to 7 loop",
            f"                if crc(0) = '1' then",
            f"                    crc := shift_right(crc, 1) xor "
            f"{_vhdl_lit(poly_val, w)};",
            f"                else",
            f"                    crc := shift_right(crc, 1);",
            f"                end if;",
            f"            end loop;",
        ]
    else:
        body += [
            f"            crc := crc xor shift_left(resize(byte, {w}), {w - 8});",
            f"            for j in 0 to 7 loop",
            f"                if crc({w - 1}) = '1' then",
            f"                    crc := shift_left(crc, 1) xor "
            f"{_vhdl_lit(poly_val, w)};",
            f"                else",
            f"                    crc := shift_left(crc, 1);",
            f"                end if;",
            f"            end loop;",
        ]

    body.append(f"        end loop;")

    if refout != refin:
        body += [
            f"        -- reflect output (refout != refin)",
            f"        reflected := (others => '0');",
            f"        for k in 0 to {w - 1} loop",
            f"            reflected(k) := crc({w - 1} - k);",
            f"        end loop;",
            f"        crc := reflected;",
        ]

    if xorout:
        body.append(
            f"        return std_logic_vector(crc xor "
            f"{_vhdl_lit(xorout, w)});"
        )
    else:
        body.append(f"        return std_logic_vector(crc);")
    body.append(f"    end function;")
    body.append("")

    body.append(_self_test_vhdl(fname, check, w))

    body.append(f"end package body;")

    return "\n".join(header + body)
