"""Codegen: profile.json -> standalone PEP 723 MCP server (Phase 7).

Reads a device profile and emits a self-contained Python file that:

- Declares its own dependencies via PEP 723 inline metadata so it
  runs with ``uv run server.py`` -- no manual ``pip install``.
- Imports only ``mcp`` and ``serial``.  Zero termapy dependency at
  runtime.
- Registers one ``@mcp.tool()`` per command in the profile, with
  typed parameters from ``typed_args``.
- Inlines the response parser logic for whatever ``response.format``
  values the profile uses (regex/lines/json/literal/none).

This is the spec-completeness test for the profile schema: if every
profile field has a Python translation, the schema is complete
enough that third parties could implement alternate consumers.

**Out of scope for v1 codegen** (could be added later if the
generated code feels short on something):

- ``error_detection`` global pattern matching.
- ``field_routing`` id correlation (NDJSON tools just readline).
- ``rate_limit_hz`` enforcement.
- Subcommands (recursive emit).
- ``async`` event surfacing as MCP notifications.

The generated server is meant to be edited.  The emit pass produces
a clean starting point; users tune from there.
"""

from __future__ import annotations

import json
import re
import textwrap
from typing import Any


# -- Public entry point ------------------------------------------------------


def emit_mcp_server(profile: dict[str, Any]) -> str:
    """Return the source of a standalone MCP server for ``profile``.

    Result is a single Python file string suitable for ``uv run``.
    """
    if not isinstance(profile, dict):
        raise TypeError("profile must be a dict")
    parts: list[str] = []
    parts.append(_emit_pep723_header(profile))
    parts.append(_emit_module_docstring(profile))
    parts.append(_emit_imports(profile))
    parts.append(_emit_transport_constants(profile))
    parts.append(_emit_open_port())
    parts.append(_emit_send_recv_helpers(profile))
    formats_used = _formats_used_by(profile)
    parsers = _emit_response_parsers(formats_used)
    if parsers:
        parts.append(parsers)
    parts.append(_emit_server_init(profile))
    for name in sorted(profile.get("commands", {})):
        cmd = profile["commands"][name]
        if not isinstance(cmd, dict):
            continue
        parts.append(_emit_tool(name, cmd, profile))
    parts.append(_emit_main())
    # Single trailing newline; double-newline between sections.
    return "\n\n".join(p.rstrip() for p in parts if p) + "\n"


# -- PEP 723 header ----------------------------------------------------------


def _emit_pep723_header(profile: dict[str, Any]) -> str:
    """The inline-script-metadata block read by uv (and PEP 723 tools)."""
    return textwrap.dedent(
        '''\
        # /// script
        # requires-python = ">=3.11"
        # dependencies = [
        #     "mcp>=1.0,<2.0",
        #     "pyserial>=3.5",
        # ]
        # ///'''
    )


# -- Module docstring + imports ----------------------------------------------


def _emit_module_docstring(profile: dict[str, Any]) -> str:
    device = profile.get("device", {}) or {}
    name = device.get("name", "<unknown device>")
    rev = profile.get("profile_revision", "")
    date = profile.get("profile_date", "")
    proto = (profile.get("transport") or {}).get("protocol", "text")
    return textwrap.dedent(
        f'''\
        """Standalone MCP server for {name}.

        Generated by ``termapy --mcp-emit``.

        Profile revision: {rev or "(unspecified)"}
        Profile date:     {date or "(unspecified)"}
        Transport:        {proto}

        Run with:
            uv run <this-file>          # PEP 723 provisions deps automatically

        Or wire into Claude Desktop's claude_desktop_config.json:
            "{_safe_id(name)}": {{
                "command": "uv",
                "args": ["run", "/path/to/this/file.py"]
            }}

        Edit freely.  This file has no termapy dependency.
        """'''
    )


def _emit_imports(profile: dict[str, Any]) -> str:
    formats = _formats_used_by(profile)
    needs_re = "regex" in formats or "lines" in formats
    lines = [
        "from __future__ import annotations",
        "",
        "import json",
        "import os",
    ]
    if needs_re:
        lines.append("import re")
    lines.append("import time")
    lines.append("from typing import Any")
    has_enum = _profile_has_enum_args(profile)
    if has_enum:
        lines.append("from typing import Literal")
    lines.append("")
    lines.append("import serial")
    lines.append("from mcp.server.fastmcp import FastMCP")
    return "\n".join(lines)


# -- Transport constants -----------------------------------------------------


def _emit_transport_constants(profile: dict[str, Any]) -> str:
    t = profile.get("transport") or {}
    proto = t.get("protocol", "text")
    return textwrap.dedent(
        f'''\
        # -- Transport configuration ----------------------------------------
        # Override PORT via the SERIAL_PORT env var; everything else is
        # baked from the profile's transport block.

        PORT: str = os.environ.get("SERIAL_PORT", "{t.get("port", "")}")
        BAUD: int = {int(t.get("baud_rate", 115200))}
        BYTE_SIZE: int = {int(t.get("byte_size", 8))}
        PARITY: str = {_pyrepr(t.get("parity", "N"))}
        STOP_BITS: float = {float(t.get("stop_bits", 1))}
        ENCODING: str = {_pyrepr(t.get("encoding", "utf-8"))}
        LINE_ENDING_SEND: str = {_pyrepr(t.get("line_ending_send", "\\n"))}
        LINE_ENDING_RECV: str = {_pyrepr(t.get("line_ending_recv", "\\n"))}
        DEFAULT_RESPONSE_TIMEOUT_S: float = {
            float(t.get("default_response_timeout_ms", 1000)) / 1000.0
        }
        INTER_COMMAND_DELAY_S: float = {
            float(t.get("inter_command_delay_ms", 0)) / 1000.0
        }
        ECHO: bool = {bool(t.get("echo", False))}
        PROMPT: str = {_pyrepr((profile.get("device") or {}).get("prompt", ""))}
        PROTOCOL: str = {_pyrepr(proto)}'''
    )


# -- Port open + send/receive helpers ----------------------------------------


def _emit_open_port() -> str:
    return textwrap.dedent(
        '''\
        # -- Serial port (opened lazily on first tool call) -----------------

        _port: serial.Serial | None = None
        _last_send: float = 0.0


        def _ensure_port() -> serial.Serial:
            """Open the serial port on first use; reuse thereafter."""
            global _port
            if _port is None or not _port.is_open:
                _port = serial.Serial(
                    port=PORT,
                    baudrate=BAUD,
                    bytesize=BYTE_SIZE,
                    parity=PARITY,
                    stopbits=STOP_BITS,
                    timeout=DEFAULT_RESPONSE_TIMEOUT_S,
                )
            return _port'''
    )


def _emit_send_recv_helpers(profile: dict[str, Any]) -> str:
    proto = (profile.get("transport") or {}).get("protocol", "text")
    if proto == "ndjson":
        return _emit_ndjson_helpers()
    return _emit_text_helpers()


def _emit_ndjson_helpers() -> str:
    return textwrap.dedent(
        '''\
        # -- NDJSON wire helpers --------------------------------------------

        _next_id: int = 0


        def _allocate_id() -> int:
            """Return a fresh request id for correlation."""
            global _next_id
            _next_id += 1
            return _next_id


        def _throttle() -> None:
            """Honor INTER_COMMAND_DELAY_S between consecutive sends."""
            global _last_send
            if INTER_COMMAND_DELAY_S > 0:
                elapsed = time.monotonic() - _last_send
                if elapsed < INTER_COMMAND_DELAY_S:
                    time.sleep(INTER_COMMAND_DELAY_S - elapsed)
            _last_send = time.monotonic()


        def _send_ndjson(payload: dict, *, fire_and_forget: bool = False) -> dict:
            """Write a JSON payload, optionally read one JSON line back.

            Returns the parsed response dict, or ``{"sent": True}`` for
            fire-and-forget commands.  On parse failure, returns
            ``{"error": "<msg>", "raw": "<text>"}``.
            """
            port = _ensure_port()
            _throttle()
            payload.setdefault("id", _allocate_id())
            line = (json.dumps(payload, separators=(",", ":")) + LINE_ENDING_SEND).encode(
                ENCODING
            )
            port.write(line)
            if fire_and_forget:
                return {"sent": True}
            raw = port.readline().decode(ENCODING, errors="replace").strip()
            if not raw:
                return {"error": "no response within timeout", "raw": ""}
            try:
                return json.loads(raw)
            except json.JSONDecodeError as e:
                return {"error": f"invalid json: {e}", "raw": raw}'''
    )


def _emit_text_helpers() -> str:
    return textwrap.dedent(
        '''\
        # -- Text-protocol wire helpers -------------------------------------


        def _throttle() -> None:
            """Honor INTER_COMMAND_DELAY_S between consecutive sends."""
            global _last_send
            if INTER_COMMAND_DELAY_S > 0:
                elapsed = time.monotonic() - _last_send
                if elapsed < INTER_COMMAND_DELAY_S:
                    time.sleep(INTER_COMMAND_DELAY_S - elapsed)
            _last_send = time.monotonic()


        def _send_text(line: str, *, fire_and_forget: bool = False) -> str:
            """Write text + line ending; return response (lines until idle).

            Read until either ``PROMPT`` appears, no data arrives within
            ``DEFAULT_RESPONSE_TIMEOUT_S``, or 32 KB collected.
            """
            port = _ensure_port()
            _throttle()
            payload = (line + LINE_ENDING_SEND).encode(ENCODING)
            port.write(payload)
            if fire_and_forget:
                return ""
            buf = bytearray()
            deadline = time.monotonic() + DEFAULT_RESPONSE_TIMEOUT_S
            while time.monotonic() < deadline and len(buf) < 32_768:
                chunk = port.read(256)
                if chunk:
                    buf.extend(chunk)
                    deadline = time.monotonic() + 0.05  # short idle timeout
                    if PROMPT and PROMPT.encode(ENCODING) in buf:
                        break
            text = buf.decode(ENCODING, errors="replace")
            if ECHO and text.startswith(line):
                text = text[len(line):]
                if text.startswith(LINE_ENDING_SEND):
                    text = text[len(LINE_ENDING_SEND):]
            if PROMPT and text.endswith(PROMPT):
                text = text[: -len(PROMPT)]
            return text.rstrip()'''
    )


# -- Response parsers (only emit what's used) --------------------------------


def _emit_response_parsers(formats: set[str]) -> str:
    """Emit parser functions for the ``response.format`` values used.

    Empty set -> empty string (NDJSON-only profiles often need only json,
    which is handled inline by _send_ndjson).  When a text profile uses
    multiple formats we emit a small dispatcher.
    """
    fns: list[str] = []
    if "regex" in formats:
        fns.append(_PARSER_REGEX)
    if "lines" in formats:
        fns.append(_PARSER_LINES)
    if "literal" in formats:
        fns.append(_PARSER_LITERAL)
    if "json" in formats:
        fns.append(_PARSER_JSON)
    if not fns:
        return ""
    return "# -- Response parsers -----------------------------------------------\n\n" + "\n\n".join(
        fns
    )


_PARSER_REGEX = textwrap.dedent(
    '''\
    def _parse_regex(text: str, pattern: str, types: dict | None = None) -> Any:
        """Apply re.search; return dict (named groups), list (positional), or string."""
        try:
            m = re.search(pattern, text)
        except re.error:
            return None
        if m is None:
            return None
        if m.groupdict():
            out = dict(m.groupdict())
            if types:
                for k, t in types.items():
                    if k in out:
                        out[k] = _coerce(out[k], t)
            return out
        if m.groups():
            return list(m.groups())
        return m.group(0)


    def _coerce(value: str, type_name: str) -> Any:
        try:
            if type_name == "int":
                return int(value, 10)
            if type_name == "float":
                return float(value)
            if type_name == "hex":
                return int(value, 16)
            if type_name == "bool":
                return value.strip().lower() in ("on", "1", "true", "yes", "t", "y")
        except (ValueError, AttributeError):
            return value
        return value'''
)


_PARSER_LINES = textwrap.dedent(
    '''\
    def _parse_lines(
        text: str,
        terminator: str = "",
        line_pattern: str = "",
        line_types: dict | None = None,
    ) -> list:
        """Split into lines; optionally truncate at terminator and per-line parse."""
        raw_lines = text.splitlines()
        if terminator:
            try:
                term_re = re.compile(terminator)
            except re.error:
                term_re = None
            if term_re is not None:
                cut = []
                for ln in raw_lines:
                    if term_re.search(ln):
                        break
                    cut.append(ln)
                raw_lines = cut
        if not line_pattern:
            return raw_lines
        try:
            line_re = re.compile(line_pattern)
        except re.error:
            return raw_lines
        out: list = []
        for ln in raw_lines:
            m = line_re.search(ln)
            if m is None:
                continue
            if m.groupdict():
                d = dict(m.groupdict())
                if line_types:
                    for k, t in line_types.items():
                        if k in d:
                            d[k] = _coerce(d[k], t)
                out.append(d)
            elif m.groups():
                out.append(list(m.groups()))
            else:
                out.append(m.group(0))
        return out'''
)


_PARSER_LITERAL = textwrap.dedent(
    '''\
    def _parse_literal(text: str, pattern: str) -> str | None:
        """Return the stripped text if it matches `pattern` exactly, else None."""
        return text.strip() if text.strip() == pattern else None'''
)


_PARSER_JSON = textwrap.dedent(
    '''\
    def _parse_json_text(text: str) -> Any:
        """json.loads with permissive error -> None."""
        try:
            return json.loads(text)
        except (json.JSONDecodeError, ValueError):
            return None'''
)


# -- Server init -------------------------------------------------------------


def _emit_server_init(profile: dict[str, Any]) -> str:
    device = profile.get("device", {}) or {}
    server_name = _safe_id(device.get("name", "device"))
    return textwrap.dedent(
        f'''\
        # -- MCP server -----------------------------------------------------

        mcp = FastMCP({_pyrepr(server_name)})'''
    )


# -- Per-command @mcp.tool() -------------------------------------------------


def _emit_tool(name: str, cmd: dict[str, Any], profile: dict[str, Any]) -> str:
    """Build one ``@mcp.tool()`` function for ``cmd``.

    The function name is the command's name with any non-identifier
    chars replaced by underscores so AT+VER becomes at_ver_; reserved
    Python keywords get a trailing underscore.
    """
    proto = (profile.get("transport") or {}).get("protocol", "text")
    func_name = _safe_id(name)
    typed_args = cmd.get("typed_args") or []
    safety = cmd.get("safety", "safe")
    response = cmd.get("response") or {}
    fmt = response.get("format", "none" if proto == "ndjson" else "lines")

    sig_parts = _build_signature(typed_args)
    docstring = _build_docstring(name, cmd)
    body = _build_body(name, cmd, proto, fmt)

    annotation = ""
    if safety == "destructive":
        annotation = (
            "@mcp.tool(annotations={\"destructiveHint\": True})\n"
        )
    elif safety == "readonly":
        annotation = "@mcp.tool(annotations={\"readOnlyHint\": True})\n"
    else:
        annotation = "@mcp.tool()\n"

    return f"{annotation}def {func_name}({sig_parts}) -> Any:\n{docstring}\n{body}"


def _build_signature(typed_args: list[dict]) -> str:
    parts: list[str] = []
    for arg in typed_args:
        if not isinstance(arg, dict):
            continue
        name = _safe_id(arg.get("name", ""))
        if not name:
            continue
        type_name = arg.get("type", "str")
        py_type = _python_type_for(type_name, arg.get("enum"))
        if arg.get("required") is False or "default" in arg:
            default = arg.get("default")
            parts.append(f"{name}: {py_type} = {_pyrepr(default)}")
        else:
            parts.append(f"{name}: {py_type}")
    return ", ".join(parts)


def _build_docstring(name: str, cmd: dict[str, Any]) -> str:
    help_text = cmd.get("help", "").strip().replace('"""', "'''")
    long_help = cmd.get("long_help", "").strip().replace('"""', "'''")
    safety = cmd.get("safety", "safe")
    lines = [f'    """{help_text}"""'] if not long_help else [
        '    """' + help_text,
        "",
        "    " + long_help.replace("\n", "\n    "),
        '    """',
    ]
    return "\n".join(lines)


def _build_body(
    name: str, cmd: dict[str, Any], proto: str, fmt: str
) -> str:
    """Generate the body lines that send the request and parse the reply."""
    typed_args = cmd.get("typed_args") or []
    arg_names = [_safe_id(a["name"]) for a in typed_args if isinstance(a, dict) and a.get("name")]
    response = cmd.get("response") or {}

    if proto == "ndjson":
        # Build args dict from typed_args
        args_lines = "    args: dict[str, Any] = {"
        args_lines += ", ".join(f'"{n}": {n}' for n in arg_names)
        args_lines += "}"
        if fmt == "none":
            return (
                f'    payload: dict[str, Any] = {{"cmd": {_pyrepr(name)}}}\n'
                f"{args_lines}\n"
                f"    if args:\n"
                f"        payload['args'] = args\n"
                f"    return _send_ndjson(payload, fire_and_forget=True)"
            )
        # NDJSON response is always JSON; _send_ndjson does the parsing.
        return (
            f'    payload: dict[str, Any] = {{"cmd": {_pyrepr(name)}}}\n'
            f"{args_lines}\n"
            f"    if args:\n"
            f"        payload['args'] = args\n"
            f"    return _send_ndjson(payload)"
        )

    # -- text protocol --
    send_template = cmd.get("send_template", "")
    if send_template:
        # Python f-string equivalent: convert {name} placeholders
        # directly.  send_template is already in Python format.
        send_expr = f"f{_pyrepr(send_template)}"
    else:
        send_expr = _pyrepr(name)

    if fmt == "none":
        return f"    _send_text({send_expr}, fire_and_forget=True)\n    return {{'sent': True}}"

    body = [f"    text = _send_text({send_expr})"]
    if fmt == "literal":
        pattern = response.get("pattern", "OK")
        body.append(
            f"    return {{'matched': _parse_literal(text, {_pyrepr(pattern)}) is not None, 'raw': text}}"
        )
    elif fmt == "regex":
        pattern = response.get("pattern", "")
        types = response.get("types") or {}
        body.append(
            f"    return _parse_regex(text, {_pyrepr(pattern)}, types={_pyrepr(types)})"
        )
    elif fmt == "lines":
        terminator = response.get("terminator", "")
        line_pattern = response.get("line_pattern", "")
        line_types = response.get("line_types") or {}
        body.append(
            "    return _parse_lines(\n"
            "        text,\n"
            f"        terminator={_pyrepr(terminator)},\n"
            f"        line_pattern={_pyrepr(line_pattern)},\n"
            f"        line_types={_pyrepr(line_types)},\n"
            "    )"
        )
    elif fmt == "json":
        body.append("    return _parse_json_text(text)")
    else:
        body.append("    return {'raw': text}")
    return "\n".join(body)


# -- Main runner -------------------------------------------------------------


def _emit_main() -> str:
    return textwrap.dedent(
        '''\
        # -- Entry point ----------------------------------------------------

        if __name__ == "__main__":
            mcp.run(transport="stdio")'''
    )


# -- Helpers -----------------------------------------------------------------


_PY_KEYWORDS = frozenset(
    {
        "False", "None", "True", "and", "as", "assert", "async", "await",
        "break", "class", "continue", "def", "del", "elif", "else", "except",
        "finally", "for", "from", "global", "if", "import", "in", "is",
        "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
        "while", "with", "yield",
    }
)


def _safe_id(name: str) -> str:
    """Coerce a command name (possibly with +./-) into a Python identifier."""
    s = re.sub(r"[^A-Za-z0-9_]+", "_", str(name).strip())
    if not s or s[0].isdigit():
        s = "_" + s
    if s in _PY_KEYWORDS:
        s += "_"
    return s.lower()


def _python_type_for(type_name: str, enum: list | None = None) -> str:
    """Map profile type names (+ optional enum) to Python type annotations."""
    base = {
        "int": "int",
        "float": "float",
        "bool": "bool",
        "hex": "int",
        "str": "str",
    }.get(type_name, "str")
    if enum and base == "str":
        # Literal["a", "b", ...]
        items = ", ".join(_pyrepr(e) for e in enum)
        return f"Literal[{items}]"
    return base


def _pyrepr(val: Any) -> str:
    """Safe Python literal repr for codegen.  Strings, numbers, dicts, lists, bool, None."""
    if isinstance(val, str):
        # Use double-quoted strings with json.dumps-style escaping.
        return json.dumps(val)
    if isinstance(val, bool):
        return "True" if val else "False"
    if val is None:
        return "None"
    if isinstance(val, (int, float)):
        return repr(val)
    if isinstance(val, dict):
        items = ", ".join(f"{_pyrepr(k)}: {_pyrepr(v)}" for k, v in val.items())
        return "{" + items + "}"
    if isinstance(val, list):
        items = ", ".join(_pyrepr(v) for v in val)
        return "[" + items + "]"
    return _pyrepr(str(val))


def _formats_used_by(profile: dict[str, Any]) -> set[str]:
    """Return the set of response.format values used by the profile."""
    out: set[str] = set()
    for cmd in (profile.get("commands") or {}).values():
        if not isinstance(cmd, dict):
            continue
        response = cmd.get("response") or {}
        fmt = response.get("format")
        if isinstance(fmt, str):
            out.add(fmt)
    return out


def _profile_has_enum_args(profile: dict[str, Any]) -> bool:
    """True if any typed_arg uses an enum constraint (drives Literal import)."""
    for cmd in (profile.get("commands") or {}).values():
        if not isinstance(cmd, dict):
            continue
        for arg in cmd.get("typed_args") or []:
            if isinstance(arg, dict) and arg.get("enum"):
                return True
    return False
