"""Refresh termapy's bundled USB vendor table from upstream usb.ids.

Reads the canonical USB ID Repository file from linux-usb.org (or a
local copy) and emits ``src/termapy/usb/_vendors_full.py`` -- a Python
module containing a single ``USB_VENDORS_FULL: dict[int, str]``
mapping every assigned USB Vendor ID to its canonical vendor name.

Why a generated Python module rather than the raw text file?

  - Runtime cost: zero parse at lookup time -- the dict is loaded by
    the normal Python import path, same as termapy's hand-curated
    ``USB_VENDORS``.
  - Termapy keeps a strict import-discipline (``cli_flags`` must not
    do I/O at import); a generated dict respects that.
  - Existing ``vendor_for(vid)`` API and call sites stay unchanged.

The generated file is committed to git.  Run this script before each
release (or whenever upstream gets a notable update) to refresh.
Diffs will typically show only newly-assigned VIDs.

Usage:

    # Fetch latest from linux-usb.org and regenerate.
    python scripts/refresh_usb_ids.py

    # Use a specific local copy (useful in air-gapped or pinned setups).
    python scripts/refresh_usb_ids.py --source path/to/usb.ids

    # Specify a custom URL (e.g. a frozen mirror or fork).
    python scripts/refresh_usb_ids.py --source https://example.com/usb.ids

The data file is plain text under a permissive redistribution
license; see https://www.linux-usb.org/usb.ids for the canonical
copy.

Stdlib only -- no requests, no third-party deps.  Safe to run in CI.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
import urllib.request
from pathlib import Path

# Default upstream URL.  linux-usb.org publishes via plain HTTP; the
# GitHub mirror is HTTPS and tends to be more reliable.
DEFAULT_SOURCE = (
    "https://raw.githubusercontent.com/usbids/usbids/master/usb.ids"
)
FALLBACK_SOURCE = "http://www.linux-usb.org/usb.ids"

# Repo paths.
REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "src" / "termapy" / "usb" / "_vendors_full.py"


def fetch(source: str) -> str:
    """Fetch the usb.ids text from a URL or local path."""
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source, timeout=30) as resp:
            data = resp.read()
    else:
        data = Path(source).read_bytes()
    # usb.ids is officially UTF-8.  Some older copies have stray non-UTF-8
    # vendor names (umlauts in trade names); fall back to latin-1 which
    # never raises.
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        return data.decode("latin-1")


# Vendor lines start at column 0 with a 4-hex VID, two spaces, then the
# vendor name.  Product lines start with a tab and are skipped.  Class
# / subclass / language sections start with a non-tab non-hex prefix
# (``C ``, ``AT ``, ``HID ``, etc.) and are also skipped.
_VENDOR_LINE = re.compile(r"^([0-9a-fA-F]{4})\s+(.+)$")


def parse_vendors(text: str) -> dict[int, str]:
    """Extract VID -> vendor-name mapping from usb.ids text."""
    vendors: dict[int, str] = {}
    for line in text.splitlines():
        # Skip comments, blank lines, product (tab-indented) lines, and
        # the class / language sections that start with a letter prefix.
        if not line or line.startswith("#") or line.startswith("\t"):
            continue
        m = _VENDOR_LINE.match(line)
        if not m:
            continue
        vid = int(m.group(1), 16)
        name = m.group(2).strip()
        vendors[vid] = name
    return vendors


def emit_python_module(vendors: dict[int, str], source_url: str) -> str:
    """Build the contents of the generated Python module.

    Emits the dict plus two metadata constants for /term.usb_db
    introspection: ``GENERATED_DATE`` (local clock when we ran the
    refresh) and ``SOURCE_URL`` (where the data came from).
    """
    today = dt.date.today().isoformat()
    sorted_items = sorted(vendors.items())
    body_lines = []
    for vid, name in sorted_items:
        # repr() handles quoting + escapes for any character including
        # non-ASCII; safer than manual escaping.
        body_lines.append(f"    0x{vid:04X}: {name!r},")
    body = "\n".join(body_lines)
    return (
        '"""USB Vendor ID -> canonical vendor name (generated).\n'
        "\n"
        "DO NOT EDIT BY HAND.  Generated by ``scripts/refresh_usb_ids.py``\n"
        "from the upstream USB ID Repository.  To refresh, run::\n"
        "\n"
        "    python scripts/refresh_usb_ids.py\n"
        "\n"
        f"Source:    {source_url}\n"
        f"Generated: {today}\n"
        f"Entries:   {len(vendors)}\n"
        "\n"
        "Used as a fallback by ``termapy.usb.vendor_for()`` when a VID\n"
        "isn't present in the curated ``USB_VENDORS`` short-form table.\n"
        "Names here are the canonical USB-IF assignments and may be long;\n"
        "``termapy.usb.mfg()`` handles narrow-column display.\n"
        '"""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "# Metadata for /term.usb_db introspection.\n"
        f"GENERATED_DATE: str = {today!r}\n"
        f"SOURCE_URL: str = {source_url!r}\n"
        "\n"
        "USB_VENDORS_FULL: dict[int, str] = {\n"
        f"{body}\n"
        "}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n", 1)[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--source",
        default=DEFAULT_SOURCE,
        help=f"URL or local path to usb.ids (default: {DEFAULT_SOURCE})",
    )
    parser.add_argument(
        "--output",
        default=str(OUTPUT_PATH),
        help=f"Path to write the Python module (default: {OUTPUT_PATH})",
    )
    args = parser.parse_args()

    print(f"==> Fetching {args.source}")
    try:
        text = fetch(args.source)
    except Exception as e:
        if args.source == DEFAULT_SOURCE:
            print(f"  primary failed ({e}); trying {FALLBACK_SOURCE}")
            text = fetch(FALLBACK_SOURCE)
            args.source = FALLBACK_SOURCE
        else:
            raise

    print(f"==> Parsing {len(text):,} bytes...")
    vendors = parse_vendors(text)
    print(f"==> Found {len(vendors):,} vendor entries")

    if len(vendors) < 1000:
        print(
            f"  warning: parsed only {len(vendors)} vendors -- did the "
            "format change?",
            file=sys.stderr,
        )

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        emit_python_module(vendors, args.source),
        encoding="utf-8",
    )
    print(f"==> Wrote {out_path}")
    print(f"OK  {len(vendors):,} vendors written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
